---
name:     AnyEvent-UserAgent
version:  0.02
abstract: 'AnyEvent::HTTP OO-wrapper'
author:
  - 'Denis Ibaev <dionys@cpan.org>'
license: perl
dynamic_config: 0
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    Test::More:          0
requires:
    AnyEvent::HTTP:      0
    HTTP::Cookies:       0
    HTTP::Message:       0
    Moo:                 0
resources:
    bugtracker: http://github.com/AdCampRu/anyevent-useragent/issues
    repository: http://github.com/AdCampRu/anyevent-useragent
    license:    http://dev.perl.org/licenses/
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
no_index:
    directory:
      - t
      - inc
      - t
